project:
  type: website

website:
  title: "Edson Silava-Junior"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com//edbbio
      - icon: twitter
        href: https://twitter.com//edbbio
format:
  html:
    theme: sandstone
    css: styles.css

editor: visual

